"""added constraint

Revision ID: 2d33073bd503
Revises: 13ee9e03eb70
Create Date: 2023-03-15 19:54:31.924840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d33073bd503'
down_revision = '13ee9e03eb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('production_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('production_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
