"""cast member production id cannot be empty

Revision ID: a6f2016e6a6c
Revises: 164dee6d88ae
Create Date: 2023-09-15 11:11:45.733463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f2016e6a6c'
down_revision = '164dee6d88ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cast_members', 'production_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cast_members', 'production_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
