"""update tables

Revision ID: 215d77bc8a4b
Revises: 022cc769621e
Create Date: 2023-03-23 08:36:26.774909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215d77bc8a4b'
down_revision = '022cc769621e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
